token:
  expiration_time: 86400000
  secret: '{cipher}AQBh60R9cGK7Gvr3OhPldUseZag+F1FqnDEqBljTt4/uJW8auE3ELVIIxTQQOAsY0i0dA1lx1WQ1Ees4FGslle7II1LtSoF4fgVALLKll7DmJoQNYt73UXgcc48P7BnpRPwHJGQHZILxSf5eiG9jBxfP29uzXJPAbUdV6z/Hq/0rkoaOYUzSA7khkh8cOCRlFBcqrC9tdppFULVehz+AEGcvwB15sRrGorm758Lezx4lZv8SDAPZrxJmX+Xsn/Oi7miWiNXDga1Xpk3sxSzR6iByoldVJQJwBWOzVJ22LQc+Whe96W/r/0+dn38h1YclE0TZ/dDM3jGsyb9JUbmTWQqjNkDroyVjKVO1fVIuMpagUywnpI26JWWHH4c9zHOakYRYs+8KU9mazFueCGs8mki0af9seiUvT5emxv5dT7860CKL1Ip+UAUMAxQ08v5H49lB45rM4DIA9cGNi50d/l36bGe3eJruRCHEKCeEX5f5LWhWm8vF3uQlguog0FmgK1zsX1/Eq2jZse1zm7yqy1Q/iTVBXLmMCwcwRVxAmsEFbg=='

gateway:
  ip: 127.0.0.1