token:
  expiration_time: 86400000
  secret: usertokenusertokenusertokenusertokenusertokenusertokenusertokenusertokenusertokenusertokenusertokenusertokenusertokenusertokendefault

gateway:
  ip: 127.0.0.1