spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

token:
  expiration_time: 86400000
  secret: usertokenusertokenusertokenusertokenusertokenusertokenusertokenusertokenusertokenusertokenusertokenusertokenusertokenusertokende

gateway:
  ip: 127.0.0.1